import { readFile, writeFile } from 'node:fs/promises'
import { pathToFileURL } from 'node:url'
import semver from 'semver'

const configUrl = new URL('../api/_config.mjs', import.meta.url)
const repository = 'JamieYee/save_website'

/** Extract the opening Markdown bullet list, excluding download tables and other sections. */
export function extractReleaseNotes(body) {
  const notes = []
  for (const line of (body ?? '').replace(/\r\n?/g, '\n').split('\n')) {
    const bullet = line.match(/^\s*[-*+]\s+(.+?)\s*$/)
    if (bullet) {
      notes.push(bullet[1])
    } else if (notes.length || (line.trim() && !/^#{1,6}\s/.test(line))) {
      break
    }
  }
  return notes.join('\n')
}

/** Pick the newest published, stable Android release with an unambiguous APK. */
export function selectAndroidRelease(releases) {
  return releases
    .filter((release) =>
      !release.draft && !release.prerelease && semver.valid(release.tag_name) &&
      Number.isFinite(Date.parse(release.published_at)),
    )
    .sort((left, right) => Date.parse(right.published_at) - Date.parse(left.published_at))
    .map((release) => {
      const apks = (release.assets ?? []).filter((asset) =>
        asset.state === 'uploaded' && /\.apk$/i.test(asset.name),
      )
      const releaseApks = apks.filter((asset) => /-release\.apk$/i.test(asset.name))
      const apk = apks.length === 1 ? apks[0] : releaseApks.length === 1 ? releaseApks[0] : null
      if (!apk || !/^https:\/\/github\.com\//.test(apk.browser_download_url)) return null
      return {
        version: semver.clean(release.tag_name),
        publishedAt: release.published_at,
        downloadUrl: apk.browser_download_url,
        releaseNotes: extractReleaseNotes(release.body),
      }
    })
    .find(Boolean) ?? null
}

/** Render the API metadata, or its safe no-download baseline when no release exists. */
export function renderConfig(release) {
  const current = release ?? {
    version: '1.0.0',
    publishedAt: '2026-01-01',
    downloadUrl: '',
    releaseNotes: '',
  }
  return `// Generated by scripts/sync-release.mjs from published GitHub Releases.\n` +
    `export const LATEST_VERSION = ${JSON.stringify(current.version)}\n` +
    `export const LATEST_PUBLISHED_AT = ${JSON.stringify(current.publishedAt)}\n` +
    `export const LATEST_DOWNLOAD_URL = ${JSON.stringify(current.downloadUrl)}\n` +
    `export const LATEST_RELEASE_NOTES = ${JSON.stringify(current.releaseNotes)}\n`
}

async function fetchAllReleases() {
  const releases = []
  for (let page = 1; page <= 10; page++) {
    const response = await fetch(`https://api.github.com/repos/${repository}/releases?per_page=100&page=${page}`, {
      headers: {
        Accept: 'application/vnd.github+json',
        'X-GitHub-Api-Version': '2022-11-28',
        ...(process.env.GITHUB_TOKEN ? { Authorization: `Bearer ${process.env.GITHUB_TOKEN}` } : {}),
      },
    })
    if (!response.ok) throw new Error(`GitHub Releases API returned ${response.status}`)
    const pageReleases = await response.json()
    if (!Array.isArray(pageReleases)) throw new Error('GitHub Releases API returned invalid data')
    releases.push(...pageReleases)
    if (pageReleases.length < 100) return releases
  }
  throw new Error('Release pagination limit reached; refusing to overwrite the current version')
}

async function main() {
  const release = selectAndroidRelease(await fetchAllReleases())
  const nextConfig = renderConfig(release)
  if (await readFile(configUrl, 'utf8') !== nextConfig) {
    await writeFile(configUrl, nextConfig)
    console.log(`Synced Android release ${release?.version ?? '(none)'}`)
  } else {
    console.log('Android release metadata is already up to date')
  }
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  await main()
}
